let data =[
    {
        img:"/images/card1.jpg",
        title:"shirt1",
        slug:"shirt1",
        price:"100",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"0",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4.7",
        numberofrating:"50",
    },
    {
        img:"/images/card2.jpg",
        title:"shirt2",
        slug:"shirt2",
        price:"110",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"73",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4.4",
        numberofrating:"160",
    },
    {
        img:"/images/card3.jpg",
        title:"shirt3",
        slug:"shirt3",
        price:"130",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"53",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4",
        numberofrating:"21",
    },
    {
        img:"/images/card4.jpg",
        title:"shirt4",
        slug:"shirt4",
        price:"180",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"24",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"3",
        numberofrating:"80",
    },
    {
        img:"/images/card5.jpg",
        title:"shirt5",
        slug:"shirt5",
        price:"145",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"26",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"3.7",
        numberofrating:"142",
    },
    {
        img:"/images/card6.jpg",
        title:"shirt6",
        slug:"shirt6",
        price:"175",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"28",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4.6",
        numberofrating:"156",
    },
    {
        img:"/images/card7.jpg",
        title:"shirt7",
        slug:"shirt7",
        price:"210",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"32",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4.1",
        numberofrating:"150",
    },
    {
        img:"/images/card8.jpg",
        title:"shirt8",
        slug:"shirt8",
        price:"70",
        description:"Easy Fashion brings you Full Sleeve Casual shirt for men in this Eid Collection of 2022. Feel comfortable and maintain your fashion hassle-free with the latest luxurious collection of casual shirts for men in Bangladesh. Shop online or visit your nearest Easy Fashion Store.",
        instock:"31",
        carddiscription:"Men Slim Fit Washed Casual ",
        rating:"4.8",
        numberofrating:"67",
    },
    
]

export default data